services:
  web:
    image: tbelbek/bensinpriser:latest
    volumes:
      - ./.env:/app/.env
      - ./prices.db:/app/prices.db
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
    networks:
      - proxy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./backup.env
    volumes:
      - ./.env:/backup/bensinpriser-env-backup:ro
      - ./prices.db:/backup/bensinpriser-data-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /D/OneDrive/Backup/Bensinpriser:/archive
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
    name: proxy_network