version: '3.8'

services:
  web:
    image: tbelbek/bensinpriser:latest
    volumes:
      - ./.env:/app/.env
      - ./prices.db:/app/prices.db
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
    networks:
      - proxy
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./backup.env
    volumes:
      - ./.env:/backup/bensinpriser-env-backup:ro
      - ./prices.db:/backup/bensinpriser-data-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /C/Users/tugha/OneDrive/Backup/Bensinpriser:/archive
networks:
  proxy:
    external: true
    name: proxy_network